#!/usr/bin/env bash
# Auto-generated by scripts/generate_launchers.py — do not commit (gitignored).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"
FRONTEND="$ROOT/frontend"

if command -v python3 >/dev/null 2>&1; then
  PY=python3
else
  PY=python
fi

if ! command -v "$PY" >/dev/null 2>&1; then
  echo "ERROR: python not found. Install Python 3.10+." >&2
  exit 1
fi

if ! command -v npm >/dev/null 2>&1; then
  echo "ERROR: npm not found. Install Node.js." >&2
  exit 1
fi

if [ ! -d "$FRONTEND/node_modules" ]; then
  echo "[INFO] Running npm install in frontend..."
  (cd "$FRONTEND" && npm install)
fi

if ! "$PY" -c "import fastapi, uvicorn" 2>/dev/null; then
  echo "[INFO] Installing Python dependencies..."
  "$PY" -m pip install -r "$ROOT/requirements.txt" --quiet
fi

echo ""
echo "========================================="
echo "  Kalshi Bot Builder — starting..."
echo "========================================="
echo "  Backend  -> http://127.0.0.1:8000 (background)"
echo "  Frontend -> http://127.0.0.1:5173 (this terminal)"
echo ""

cleanup() {
  if [ -n "${UV_PID:-}" ] && kill -0 "$UV_PID" 2>/dev/null; then
    kill "$UV_PID" 2>/dev/null || true
  fi
}
trap cleanup EXIT INT TERM

(cd "$ROOT" && "$PY" -m uvicorn backend.main:app --reload --host 127.0.0.1 --port 8000) &
UV_PID=$!

sleep 2
cd "$FRONTEND"
npm run dev
