#!/usr/bin/env python3
"""
Write launch.ps1, launch.bat, and launch.sh into the application root (parent of scripts/).

Normally this runs automatically during frontend install on Windows, macOS, and Linux:

    cd frontend && npm install

You can also run manually from the PredictionMarketApp directory:

    python scripts/generate_launchers.py

Generated files are gitignored so each machine keeps its own copies.
"""

from __future__ import annotations

import os
import stat
import sys
from pathlib import Path

# Application root = parent of scripts/
ROOT = Path(__file__).resolve().parent.parent

LAUNCH_PS1 = r'''# Auto-generated by scripts/generate_launchers.py — do not commit (gitignored).
# Start Kalshi Bot Builder: FastAPI (8000) + Vite dev server (5173)
# Usage:  .\launch.ps1
#         powershell -NoProfile -ExecutionPolicy Bypass -File .\launch.ps1

$ErrorActionPreference = "Stop"
$Root = $PSScriptRoot
$FrontendDir = Join-Path $Root "frontend"
$AppUrl = "http://localhost:5173/"

Write-Host ""
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "   Kalshi Bot Builder — Launching...   " -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

$VenvPy = Join-Path $Root ".venv\Scripts\python.exe"
if (Test-Path $VenvPy) {
    $Py = $VenvPy
} elseif (Get-Command python -ErrorAction SilentlyContinue) {
    $Py = "python"
} else {
    Write-Host "ERROR: Python not found. Run install.ps1 or install.bat once, then retry." -ForegroundColor Red
    pause; exit 1
}

if (-not (Get-Command npm -ErrorAction SilentlyContinue)) {
    Write-Host "ERROR: npm not found on PATH. Install Node.js and retry." -ForegroundColor Red
    pause; exit 1
}

$nodeModules = Join-Path $FrontendDir "node_modules"
if (-not (Test-Path $nodeModules)) {
    Write-Host "node_modules not found — running npm install..." -ForegroundColor Yellow
    Push-Location $FrontendDir
    npm install
    Pop-Location
    Write-Host "npm install complete." -ForegroundColor Green
}

$check = & $Py -c "import fastapi, uvicorn" 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "Missing Python dependencies — run install.ps1 or: pip install -r requirements.txt" -ForegroundColor Yellow
    & $Py -m pip install -r (Join-Path $Root "requirements.txt") --quiet
    Write-Host "pip install complete." -ForegroundColor Green
}

foreach ($port in @(8000, 5173)) {
    Get-NetTCPConnection -State Listen -LocalPort $port -ErrorAction SilentlyContinue |
        ForEach-Object {
            Stop-Process -Id $_.OwningProcess -Force -ErrorAction SilentlyContinue
        }
}
Start-Sleep -Seconds 1

$backendCmd = @"
`$host.UI.RawUI.WindowTitle = 'Kalshi Backend :8000'
Set-Location -LiteralPath '$Root'
Write-Host ''
Write-Host '  Backend  http://127.0.0.1:8000' -ForegroundColor Cyan
Write-Host '  Press Ctrl+C to stop.' -ForegroundColor DarkGray
Write-Host ''
& $Py -m uvicorn backend.main:app --reload --port 8000
Write-Host ''
Write-Host 'Backend stopped.' -ForegroundColor Yellow
pause
"@

Start-Process powershell.exe -ArgumentList @(
    "-NoExit", "-NoProfile", "-Command", $backendCmd
)

Start-Sleep -Seconds 3

$frontendCmd = @"
`$host.UI.RawUI.WindowTitle = 'Kalshi Frontend :5173'
Set-Location -LiteralPath '$FrontendDir'
Write-Host ''
Write-Host '  Frontend  http://localhost:5173' -ForegroundColor Cyan
Write-Host '  Press Ctrl+C to stop.' -ForegroundColor DarkGray
Write-Host ''
npm run dev
Write-Host ''
Write-Host 'Frontend stopped.' -ForegroundColor Yellow
pause
"@

Start-Process powershell.exe -ArgumentList @(
    "-NoExit", "-NoProfile", "-Command", $frontendCmd
)

Start-Sleep -Seconds 4
Start-Process $AppUrl

Write-Host ""
Write-Host "  Backend  -> http://127.0.0.1:8000" -ForegroundColor Green
Write-Host "  Frontend -> $AppUrl" -ForegroundColor Green
Write-Host ""
Write-Host "Two windows opened. Close them (Ctrl+C) to stop the app." -ForegroundColor DarkGray
Write-Host ""
'''

LAUNCH_BAT = r'''@echo off
REM Auto-generated by scripts/generate_launchers.py
setlocal
cd /d "%~dp0"
powershell -NoProfile -ExecutionPolicy Bypass -File "%~dp0launch.ps1"
endlocal
'''

LAUNCH_SH = r'''#!/usr/bin/env bash
# Auto-generated by scripts/generate_launchers.py — do not commit (gitignored).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")" && pwd)"
cd "$ROOT"
FRONTEND="$ROOT/frontend"

if [ -x "$ROOT/.venv/bin/python" ]; then
  PY="$ROOT/.venv/bin/python"
elif command -v python3 >/dev/null 2>&1; then
  PY=python3
elif command -v python >/dev/null 2>&1; then
  PY=python
else
  echo "ERROR: python not found. Run ./install.sh once, then retry." >&2
  exit 1
fi

if ! command -v npm >/dev/null 2>&1; then
  echo "ERROR: npm not found. Install Node.js." >&2
  exit 1
fi

if [ ! -d "$FRONTEND/node_modules" ]; then
  echo "[INFO] Running npm install in frontend..."
  (cd "$FRONTEND" && npm install)
fi

if ! "$PY" -c "import fastapi, uvicorn" 2>/dev/null; then
  echo "[INFO] Installing Python dependencies..."
  "$PY" -m pip install -r "$ROOT/requirements.txt" --quiet
fi

echo ""
echo "========================================="
echo "  Kalshi Bot Builder — starting..."
echo "========================================="
echo "  Backend  -> http://127.0.0.1:8000 (background)"
echo "  Frontend -> http://127.0.0.1:5173 (this terminal)"
echo ""

cleanup() {
  if [ -n "${UV_PID:-}" ] && kill -0 "$UV_PID" 2>/dev/null; then
    kill "$UV_PID" 2>/dev/null || true
  fi
}
trap cleanup EXIT INT TERM

(cd "$ROOT" && "$PY" -m uvicorn backend.main:app --reload --host 127.0.0.1 --port 8000) &
UV_PID=$!

sleep 2
cd "$FRONTEND"
npm run dev
'''


def main() -> int:
    if not (ROOT / "backend").is_dir() or not (ROOT / "frontend").is_dir():
        print("ERROR: Run this from the app root (folder containing backend/ and frontend/).", file=sys.stderr)
        print(f"  Expected root: {ROOT}", file=sys.stderr)
        return 1

    (ROOT / "launch.ps1").write_text(LAUNCH_PS1, encoding="utf-8", newline="\r\n")
    (ROOT / "launch.bat").write_text(LAUNCH_BAT, encoding="utf-8", newline="\r\n")
    sh_path = ROOT / "launch.sh"
    sh_path.write_text(LAUNCH_SH, encoding="utf-8", newline="\n")
    mode = sh_path.stat().st_mode
    sh_path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    print(f"Wrote launch scripts into: {ROOT}")
    print("  - launch.ps1")
    print("  - launch.bat")
    print("  - launch.sh (executable on Unix)")
    print("")
    print("Windows:  .\\launch.ps1   or   launch.bat")
    print("macOS/Linux:  ./launch.sh")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
