#!/usr/bin/env python3
"""
Write thin launch.bat / launch.sh that call scripts/launch.py (same behavior on every OS).

Generated files are gitignored — never commit them.

    python scripts/generate_launchers.py

Runs automatically from:  cd frontend && npm install
"""

from __future__ import annotations

import os
import stat
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# Windows: double-click friendly
LAUNCH_BAT = r"""@echo off
REM Auto-generated by scripts/generate_launchers.py — do not commit (gitignored).
cd /d "%~dp0"
if exist ".venv\Scripts\python.exe" (
  ".venv\Scripts\python.exe" scripts\launch.py
) else (
  py -3 scripts\launch.py 2>nul || python scripts\launch.py
)
if errorlevel 1 pause
"""

# macOS / Linux
LAUNCH_SH = r"""#!/usr/bin/env sh
# Auto-generated by scripts/generate_launchers.py — do not commit (gitignored).
cd "$(dirname "$0")" || exit 1
if [ -x ".venv/bin/python" ]; then
  exec .venv/bin/python scripts/launch.py
fi
if command -v python3 >/dev/null 2>&1; then
  exec python3 scripts/launch.py
fi
exec python scripts/launch.py
"""


def main() -> int:
    if not (ROOT / "backend").is_dir() or not (ROOT / "frontend").is_dir():
        print("ERROR: Run from app root (folder containing backend/ and frontend/).", file=sys.stderr)
        print(f"  Expected root: {ROOT}", file=sys.stderr)
        return 1

    # Remove legacy launch.ps1 if present (older installs)
    legacy_ps1 = ROOT / "launch.ps1"
    if legacy_ps1.is_file():
        try:
            legacy_ps1.unlink()
        except OSError:
            pass

    (ROOT / "launch.bat").write_text(LAUNCH_BAT, encoding="utf-8", newline="\r\n")
    sh_path = ROOT / "launch.sh"
    sh_path.write_text(LAUNCH_SH, encoding="utf-8", newline="\n")
    mode = sh_path.stat().st_mode
    sh_path.chmod(mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

    print(f"Wrote local launch shortcuts into: {ROOT}")
    print("  - launch.bat   (Windows: double-click or run from cmd)")
    print("  - launch.sh    (macOS/Linux: chmod +x once, then ./launch.sh)")
    print("")
    print("Or from this folder, any OS:")
    print("  python scripts/launch.py")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
